mini_blog/config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
      resources :replies
      resources :likes
  end
   root 'blogs#index'

end

mini_blog/app/models/blog.rb
class Blog < ActiveRecord::Base
    has_many :replies, dependent: :destroy
    has_many :likes, dependent: :destroy
    default_scope -> { order(created_at: :desc) }
end

mini_blog/app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :blog, counter_cache: :like
end

mini_blog/app/models/reply.rb
class Reply < ActiveRecord::Base
    belongs_to :blog
end

mini_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

mini_blog/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only: [:show,:update]
  def index
      @blogs = Blog.all
      @blog = Blog.new
  end

  def create
   @blog = Blog.new(blogs_params)
   @blog.save
    redirect_to blogs_path
  end

  def show
    @reply = @blog.replies.build
    @replies = @blog.replies
  end

  private
   def blogs_params
     params.require(:blog).permit(:body)
   end

   def set_blog
   @blog = Blog.find(params[:id])
  end
end

mini_blog/app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
    @like = Like.new(blog_id: params[:blog_id])
    @like.save
     redirect_to blogs_path
      end
end

mini_blog/app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    @reply = Reply.new(reply_params)
    @blog = @reply.blog
      @reply.save
    redirect_to blog_path(@blog)
  end

  private
    # ストロングパラメーター
    def reply_params
      params.require(:reply).permit(:blog_id, :comment)
    end

end

mini_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

mini_blog/app/helpers/blogs_helper.rb
module BlogsHelper
end

mini_blog/app/helpers/likes_helper.rb
module LikesHelper
end

mini_blog/app/helpers/replies_helper.rb
module RepliesHelper
end

mini_blog/app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <%=  f.text_field :body %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

mini_blog/app/views/blogs/index.html.erb
<h1>Naokiのブログ</h2>
<%= render 'form' %>
<% @blogs.each do |blog| %>
  <p><%= blog.id %>：
  <%= link_to blog_path(blog) do %>
      <%= blog.body %></p>
  <% end %>
  <strong>投稿日時:</strong>
  <%= blog.created_at.strftime("%y/%m/%d %p %l:%M") %>
 <%= render partial: 'likes/like', locals: { like: @like, blog: blog } %>
  <p>コメント数：<%= blog.replies.count %></p>
  <br>
<% end %>

mini_blog/app/views/blogs/show.html.erb
      <p ><strong>内容：<%= @blog.body %></strong></p>
      <p ><strong>いいね：<%= @blog.like %></strong></p>
      <p >
        <strong>投稿日時:</strong>
        <%= @blog.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    <p>コメント一覧</p>
      <%= render partial: 'replies/index', locals: { replies: @replies, blog: @blog } %>
    <%= render partial: 'replies/form', locals: { reply: @reply, blog: @blog } %>
    <%= link_to '戻る', blogs_path %>
  </div>
</div>

mini_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

mini_blog/app/views/likes/_like.html.erb
<table><tr>
    <td>
<%= button_to blog_likes_path(blog), id: "like-button" do %>
    <span>いいね</span>
  <% end %>
  </td>
  <td>
    <p>：<%= blog.like %><p>
  </td>
  </tr>
  <table>

mini_blog/app/views/replies/_form.html.erb
<%= form_for([blog,reply]) do |f| %>
  <%= f.hidden_field :blog_id %>
    <%= f.text_field :comment  %>
    <%= f.submit "コメント"%>
<% end %>

mini_blog/app/views/replies/_index.html.erb

  <% replies.each do |reply| %>
        <p><%= reply.comment %></p>
  <% end %>